import type { CartItem, Store } from '@/types'
import { createClient } from '@/lib/supabase/client'
import { formatPrice } from '@/lib/currency'
import { effectivePrice } from '@/lib/price'

const ar = (n: number) => n.toLocaleString('ar-EG')

export function normalizeEgyptianNumber(number: string): string {
  const digits = number.replace(/\D/g, '')
  if (digits.startsWith('20')) return digits
  if (digits.startsWith('0')) return '20' + digits.slice(1)
  return '20' + digits
}

// Short, stable order reference derived from the order id — the SAME code the
// merchant sees in the dashboard, so they can match the WhatsApp message to it.
export function orderCode(id: string): string {
  return '#' + id.replace(/-/g, '').slice(0, 4).toUpperCase()
}

// Renders a cart line, e.g. "• ٢× تيشيرت (المقاس: M) — ٣٠٠ جنيه"
function lineLabel(item: CartItem, currency: string): string {
  const { product, quantity, selectedOptions } = item
  const opts = selectedOptions && Object.keys(selectedOptions).length
    ? ` (${Object.entries(selectedOptions).map(([k, v]) => `${k}: ${v}`).join('، ')})`
    : ''
  return `• ${ar(quantity)}× ${product.name}${opts} — ${formatPrice(effectivePrice(product) * quantity, currency)}`
}

type Customer = {
  name: string
  phone: string
  address?: string
  notes?: string
  discount?: { code: string; amount: number }
}

export function buildWhatsAppOrderUrl(
  store: Store,
  cart: CartItem[],
  customer: Customer,
  orderRef?: string
): string {
  const whatsappNumber = normalizeEgyptianNumber(store.whatsapp_number)
  const lines = cart.map((item) => lineLabel(item, store.currency))
  const subtotal = cart.reduce((sum, { product, quantity }) => sum + effectivePrice(product) * quantity, 0)
  const deliveryFee = Number(store.delivery_fee || 0)
  const discount = customer.discount?.amount ?? 0
  const total = Math.max(0, subtotal - discount) + deliveryFee
  const showBreakdown = deliveryFee > 0 || discount > 0

  // The customer's opening line — the merchant can customise it; default otherwise.
  const greeting = store.message_template?.trim()
    ? store.message_template.trim()
    : `مرحباً! حابب أطلب من ${store.name} 🛍️`

  // Clean, WhatsApp-native message (uses *bold* for scannability). We do NOT echo
  // the merchant's own payment methods back to them — the customer saw those in the
  // cart, and the closing line asks the merchant to confirm the payment method.
  const message = [
    greeting,
    ``,
    `📦 *تفاصيل الطلب*`,
    ...(orderRef ? [`رقم الطلب: ${orderRef}`] : []),
    ...lines,
    ``,
    ...(showBreakdown ? [`المجموع الفرعي: ${formatPrice(subtotal, store.currency)}`] : []),
    ...(discount > 0 ? [`خصم (${customer.discount!.code}): −${formatPrice(discount, store.currency)}`] : []),
    ...(deliveryFee > 0 ? [`الشحن: ${formatPrice(deliveryFee, store.currency)}`] : []),
    `*الإجمالي: ${formatPrice(total, store.currency)}*`,
    ``,
    `📋 *بياناتي*`,
    `الاسم: ${customer.name}`,
    `الهاتف: ${customer.phone}`,
    ...(customer.address?.trim() ? [`العنوان: ${customer.address.trim()}`] : []),
    ...(customer.notes?.trim() ? [`ملاحظات: ${customer.notes.trim()}`] : []),
    ``,
    `من فضلك أكّد الطلب وقول لي طريقة الدفع 🙏`,
  ].join('\n')

  return `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`
}

// Saves the order to the dashboard. The id is generated by the caller and passed
// in (the orders table is owner-only on SELECT, so an anonymous customer can't read
// back an auto-generated id — generating it client-side lets us show a matching
// order reference without exposing the row). Throws on failure.
export async function saveOrder(
  store: Store,
  cart: CartItem[],
  customer: Customer,
  orderId: string
): Promise<void> {
  const supabase = createClient()
  const subtotal = cart.reduce((sum, { product, quantity }) => sum + effectivePrice(product) * quantity, 0)
  const discount = customer.discount?.amount ?? 0
  const total = Math.max(0, subtotal - discount) + Number(store.delivery_fee || 0)
  const items = cart.map(({ product, quantity, selectedOptions }) => ({
    name: product.name,
    quantity,
    price: effectivePrice(product),
    options: selectedOptions && Object.keys(selectedOptions).length ? selectedOptions : null,
  }))
  const { error } = await supabase.from('orders').insert({
    id: orderId,
    store_id: store.id,
    items,
    total,
    customer_name: customer.name,
    customer_phone: customer.phone,
    customer_address: customer.address?.trim() || null,
    notes: customer.notes?.trim() || null,
    coupon_code: customer.discount?.code ?? null,
  })
  if (error) throw error
}
